apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bincalc
  template:
    metadata:
      labels:
        app: bincalc
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/project-e3d98e07-b588-4684-81a/sofe3980u/binarycalculator
          name: bincalc
          ports:
            - containerPort: 8080
              name: bincalc
